name: 'Westblat Custom Docker Deploy'
description: 'Builds, Pushes, Syncs Compose, and Deploys'

inputs:
  ssh_host:
    required: true
  ssh_user:
    required: true
  ssh_key:
    required: true
  ghcr_user:
    required: true
  ghcr_token:
    required: true
  image_name:
    description: 'Optional sub-name (e.g. web). Leave blank for root image.'
    required: false
    default: ''
  env_file:
    description: 'Full content of .env file from secrets'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}${{ inputs.image_name != '' && format('/{0}', inputs.image_name) || '' }}
        tags: type=ref,event=tag

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Prepare .env file
      if: ${{ inputs.env_file_content != '' }}
      shell: bash
      run: |
        echo "${{ inputs.env_file_content }}" > env.tmp

    - name: Copy Docker Compose and env to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        source: "docker-compose.yml,env.tmp"
        target: "~/${{ github.event.repository.name }}/"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        script: |
          echo "${{ inputs.ghcr_token }}" | docker login ghcr.io -u ${{ inputs.ghcr_user }} --password-stdin
          cd ~/${{ github.event.repository.name }}
          if [ -f env.tmp ]; then mv env.tmp .env; fi
          export IMAGE_TAG=${{ github.ref_name }}
          export GITHUB_REPOSITORY=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          export IMAGE_NAME_SUFFIX="${{ inputs.image_name }}"
          docker compose pull
          docker compose up -d
          docker image prune -f
